"""E4 -- a ledger the person can read and correct.

The claim in the plan is worth restating because it is the whole argument:

> **Making memory legible is a cheaper path to accuracy than making
> extraction smarter.**

Every other lever in this field is spent on better extraction -- bigger
models, better prompts, cleverer chunking -- to reduce the rate at which
wrong things get stored. That is worth doing and it has a ceiling. The
second-order effect of a readable ledger is larger and almost free: once
people can SEE what a system believes about them, they correct it
proactively, and they correct the things that matter to them rather than
the things a benchmark happens to measure.

THREE DESIGN COMMITMENTS.

**A correction is evidence, not an edit.** The original observation is never
rewritten -- the append-only trigger would reject it, and rightly. A
correction is a new node that supersedes, so `why()` shows both what was
believed and who changed it. "The system used to think X, until Bill said
otherwise on the 14th" is a more useful record than X having quietly become
Y.

**A person correcting something is the deepest possible encoding.** They
retrieved it, evaluated it, and generated a replacement -- the generation
effect in the levels-of-processing literature, and the reason a correction
is logged as a maximum-depth exposure. Someone who corrected a fact will
remember it far longer than someone who was told it, and the transactive
model should know that.

**A correction cannot launder a guess into a fact.** A user correcting a
hypothesis produces a corrected *hypothesis*, because monotonicity applies
to corrections like everything else. What the user asserts on their own
authority is `user_utterance` and enters as evidence; what they fix about a
derived claim stays derived.
"""
from __future__ import annotations

from dataclasses import dataclass, field

# A correction is generated by the person, not received. Levels of
# processing: generation beats evaluation beats reading, and this is the top
# of that scale.
CORRECTION_DEPTH = 2.0


@dataclass
class LedgerEntry:
    node_id: str
    content: str
    kind: str                   # "observation" | "derived"
    epistemic: str
    confidence: float
    source_ref: str
    when: float
    corrected: bool = False
    corrected_by: str = ""
    supersedes: str = ""

    @property
    def editable(self) -> bool:
        """Everything is correctable. Nothing is editable.

        The distinction is the point: you cannot change what the record
        says, only add a better record that supersedes it.
        """
        return True

    def render(self) -> str:
        mark = "  [corrected]" if self.corrected else ""
        fact = "" if self.epistemic in ("observed", "reported") else \
            f"  *{self.epistemic}, not fact*"
        return f"- {self.content}{fact}{mark}\n  <sub>{self.source_ref}</sub>"


@dataclass
class Ledger:
    entries: list[LedgerEntry] = field(default_factory=list)
    partition: str = "default"

    def render(self) -> str:
        """A surface someone will actually read.

        Grouped by whether it is evidence or inference, because the first
        question a person asks of a memory about them is "did I say that, or
        did you decide it?" -- and a flat list makes that unanswerable
        without reading every line.
        """
        seen = [e for e in self.entries if e.kind == "observation"]
        thought = [e for e in self.entries if e.kind != "observation"]
        L = [f"# What I have on record — `{self.partition}`", ""]
        L.append("Anything here can be corrected. Corrections do not erase "
                 "the original;")
        L.append("they supersede it, and both stay visible in `why()`.")
        L.append("")
        if seen:
            L += ["## Things I was told or shown", ""]
            L += [e.render() for e in seen] + [""]
        if thought:
            L += ["## Things I worked out myself", "",
                  "**These are not facts.** If one is wrong, correcting it "
                  "is more valuable than", "correcting an observation — a "
                  "wrong inference is load-bearing for everything", "derived "
                  "from it.", ""]
            L += [e.render() for e in thought] + [""]
        if not self.entries:
            L.append("*Nothing on record for this partition.*")
        return "\n".join(L).strip()


def correction_note(original: str, corrected: str, by: str,
                    reason: str = "") -> str:
    """The text of the correction node itself.

    Carries what it replaced. A correction that only states the new value
    loses the fact that a specific wrong thing was believed, which is the
    part an audit needs.
    """
    note = corrected.strip()
    tail = f" (corrected by {by}"
    if reason:
        tail += f": {reason}"
    tail += f"; was: {original.strip()!r})"
    return note + tail
